name: ci

on: [push]

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2
    - name: Test code
      run: go test -v ./...
